import jsPDF from 'jspdf';
import { IRP5Data } from '@/types/tax';
import { 
  initializePDFWithUTF8Support, 
  renderTextSafe, 
  renderSectionHeader 
} from './fontUtils';

export interface PDFReportOptions {
  includeCharts?: boolean;
  includeRecommendations?: boolean;
  watermark?: string;
  branding?: {
    logo?: string;
    companyName?: string;
    colors?: {
      primary: string;
      secondary: string;
    };
  };
}

export function generatePDFReport(
  data: IRP5Data,
  options: PDFReportOptions = {}
): jsPDF {
  const doc = initializePDFWithUTF8Support();
  
  // Add title
  renderTextSafe(doc, 'Tax Calculation Report', 20, 30, {
    fontSize: 20,
    fontStyle: 'bold',
    color: [0, 0, 0]
  });
  
  // Add basic information
  renderTextSafe(doc, `Tax Year: ${data.taxYear}`, 20, 50, {
    fontSize: 12,
    color: [0, 0, 0]
  });
  renderTextSafe(doc, `Gross Remuneration: R${data.grossRemuneration.toLocaleString()}`, 20, 65, {
    fontSize: 12,
    color: [0, 0, 0]
  });
  renderTextSafe(doc, `PAYE Withheld: R${data.payeWithheld.toLocaleString()}`, 20, 80, {
    fontSize: 12,
    color: [0, 0, 0]
  });
  renderTextSafe(doc, `Total Tax: R${data.totalTax.toLocaleString()}`, 20, 95, {
    fontSize: 12,
    color: [0, 0, 0]
  });
  
  // Add calculated fields if available
  if (data.taxableIncome) {
    renderTextSafe(doc, `Taxable Income: R${data.taxableIncome.toLocaleString()}`, 20, 110, {
      fontSize: 12,
      color: [0, 0, 0]
    });
  }
  
  if (data.refundDue) {
    renderTextSafe(doc, `Refund Due: R${data.refundDue.toLocaleString()}`, 20, 125, {
      fontSize: 12,
      color: [0, 0, 0]
    });
  }
  
  // Add branding if provided
  if (options.branding?.companyName) {
    renderTextSafe(doc, `Generated by ${options.branding.companyName}`, 20, 280, {
      fontSize: 10,
      color: [0, 0, 0]
    });
  }
  
  return doc;
} 